"""Source registration for P0 arithmetic probes."""

from __future__ import annotations

from amora.core.artifacts import read_package_text, sha256_text
from amora.schemas.results import EvidenceTier, ParameterEstimate, ProbeArtifact, ProbeResult


ARITHMETIC_SOURCES = ("dependent_chain.cu", "independent_chains.cu")


def arithmetic_source_probe() -> ProbeResult:
    artifacts: list[ProbeArtifact] = []
    for source in ARITHMETIC_SOURCES:
        text = read_package_text(__package__, source)
        artifacts.append(
            ProbeArtifact(
                kind="cuda_source",
                path=f"amora/probes/nvidia/p0/arithmetic_latency/{source}",
                sha256=sha256_text(text),
            )
        )

    estimates = [
        ParameterEstimate(
            name="shader_core_config::max_sp_latency",
            value=None,
            evidence=EvidenceTier.TIMING_DIRECT,
            confidence=0.0,
            unit="cycles",
            risk="medium",
            notes=("Generated by dependent_chain.cu; requires CUDA execution.",),
        ),
        ParameterEstimate(
            name="shader_core_config::pipe_widths",
            value=None,
            evidence=EvidenceTier.COUPLED_INFERENCE,
            confidence=0.0,
            risk="medium_high",
            notes=("Generated by independent_chains.cu throughput saturation.",),
        ),
    ]

    return ProbeResult(
        name="arithmetic_latency/source_generation",
        tier="P0",
        status="planned",
        artifacts=artifacts,
        estimates=estimates,
    )
